### ISSUE TITLE
Cannot open Tableau Files

### ISSUE THREAD

**Issue by stevepepple** [BayAreaMetro/pems-typical-weekday#1]
When I try to open either of the Tableau files, there as an error regarding a missing file, pems_period.tde.

I don't see this file in the github folder. 

![missing-file](https://cloud.githubusercontent.com/assets/466699/8577369/197d2512-255d-11e5-9efe-07058c1d1495.jpg)

**Comment by DavidOry** [comment]
Many apologies for the delayed reply.

Tableau converts the CSV files I point to in the README into Tableau Data Extracts.  I store these extracts locally.  When you open up Tableau, navigate to the `Data Source` tab and point to your local copy of the CSV files.  Then rebuild the extract. 

I've added some notes to this effect in the README.
